Fix refmt version message warning (#2216)
* Fix refmt version message warning

Needs a new line, otherwise it looks like this:

```
Warn: refmt version missed, it is recommended to set it explicitly since we may change the default in the futureFile "bsconfig.json", line 3:
Error: JSX version 3...
```

Thanks for putting the warning too.

* Use @.